using TrixiBase
using Tenkai
using Tenkai.TenkaicRK

trixi_include(joinpath(@__DIR__, "run_tenmom_two_rare_source_super_stiff.jl"),
              nx = 500,
              saveto = joinpath(@__DIR__, "tmp_super_stiff_nx500"))

## Reference data is provided in the repository, but can be regenerated by uncommenting
## the following line. Note that this takes some time to run.
# trixi_include(joinpath(@__DIR__, "run_tenmom_two_rare_source_super_stiff.jl"),
#               degree = 0, solver = cIMEX111(), limiter = setup_limiter_none(),
#               nx = 100000,
#               saveto = joinpath(@__DIR__, "ref_nx100000"))

trixi_include(joinpath(@__DIR__, "run_tenmom_two_rare_source_super_stiff.jl"),
              nx = 1000,
              saveto = joinpath(@__DIR__, "tmp_super_stiff_nx1000"))

